### PR TITLE
Add Heroku app.json

### PR DESCRIPTION
**Pull request by pcreux**
Add heroku's `app.json` to auto-setup add-ons, env vars and run migrations on deploy. It also enables heroku to automagically create a temporary heroku app for each PR.

Special thanks to @dmathieu for his lovely support.

### CODE REVIEW

**Comment by pcreux** [comment]
screen shot 2015-11-17 at 5 50 52 pm

...?

Contacting Heroku support. :)

**Comment by dmathieu** [comment]
An app by the name `brewhouse-rails-template-pr-31` already exists on the platform.
It looks like it's owned by you @pcreux

**Comment by pcreux** [comment]
@dmathieu Oh, ok thanks! I didn't see it.

So the app was created but then failed to deployed because `app.json` was invalid. Let me clean that up.

**Comment by dmathieu** [comment]
And it looks it properly deployed now :tada:

**Comment by pcreux** [comment]
@dmathieu Thanks for you help! :green_heart:

**Pull request merged**
